apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-server-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-save-games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
