apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-server-files
spec:
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-save-games
spec:
  resources:
    requests:
      storage: 5Gi
